language: python
python:
  - "3.5"
install:
  - pip install -r ./requirements.txt
script:
  - python main.py 2 1 5 3
  - python main.py 1 100 0 1
  - python main.py 0 1 -1 100
  - python main.py 0 -1 1 100
